polls/urls.py
from django.urls import path
from .views import *

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', FarmListView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('<int:pk>/growth/', GrowthView.as_view(), name='growth'),
    path('<int:pk>/manage/', ManageView.as_view(), name='manage'),
]

smartfarmapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

class Farm(models.Model):
    farm_name=models.CharField(max_length=200)
    def __str__(self):
        return self.farm_name
        
class Growth(models.Model): # 생장 클래스
    farm_name=models.ForeignKey(Farm,on_delete=models.SET_NULL,null=True)
    pub_date=models.DateTimeField('date published')
    flower_part=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 개화부 경경
    growpoint_shape=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 생장점 엽형태
    leaf_size=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 잎 크기
    geodetic_form=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 측지형태
    stem_color=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) #줄기색
    flower_size=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 꽃 크기
    root_form=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) #뿌리형태/냄새
    weekly_growth=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) #주간절간생장
    
    fruit_load=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 착과부하수/m2
    number_bloom=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 개화 꽃잎수
    growpoint_leafcolor=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 생장점 엽색
    flower_shape=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 꽃자루 형태
    flower_distance=models.IntegerField(default=0,validators=[MinValueValidator(-2),MaxValueValidator(2)]) # 개화부위 거리
    
    def __str__(self):
        return str(self.pub_date)+"["+str(self.farm_name)+"]"+"[Growth]"
    def was_published_recently(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)
    
class Manage(models.Model): # 환경관리 클래스
    farm_name=models.ForeignKey(Farm,on_delete=models.SET_NULL,null=True)
    pub_date=models.DateTimeField('date published') # 날짜
    temp=models.FloatField(default=20.0) # 24시간평균온도
    DIF_AM=models.FloatField(default=0) # DIF 오전
    DIF_PM=models.FloatField(default=0) # DIF 오후
    D=models.TimeField(default=timezone.now) # 주간시간
    N=models.TimeField(default=timezone.now) # 야간시간
    HD=models.FloatField(default=0) # HD
    Pband=models.FloatField(default=0) # P-Band
    CO=models.IntegerField(default=0) # CO2
    Light=models.IntegerField(default=0) #차광
    WC=models.IntegerField(default=0) # WC
    StartW=models.IntegerField(default=0) # 급액시작
    EndW=models.IntegerField(default=0) # 급액종료
    WEC=models.FloatField(default=0) # 급액EC
    WRatio=models.IntegerField(default=0) # 배액율
    wtype_choice=[('ds','다량소회'),('sd','소량다회')] #급액방식
    WType=models.CharField(max_length=30, choices=wtype_choice)
    RHead=models.CharField(max_length=10, choices=[('False','무'),('True','유')]) # 적심
    RLeaf=models.CharField(max_length=10, choices=[('False','무'),('True','유')]) # 적엽
    RFruit=models.CharField(max_length=10, choices=[('False','무'),('True','유')]) #적과
    Overload=models.FloatField(default=0) # 착과부하
    geo_choice=[('fs','2~3매'),('sc','1~2매'),('no','무')] # 측지확보
    Geodetic=models.CharField(max_length=40, choices=geo_choice)
    LAI=models.FloatField(default=0) # LAI
    acc_light=models.IntegerField(default=0) # 누적광량
    def __str__(self):
        return str(self.pub_date)+"["+str(self.farm_name)+"]"+"[Manage]"
    def was_published_recently(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)

polls/views.py
from django.shortcuts import render,redirect
from .models import Growth,Farm,Manage
from django.views import generic
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy

farm_id=None
# Create your views here.
class FarmListView(ListView):
    model=Farm
    def form_valid(self,form):
        farm_id=self.request.farm.id
        
class DetailView(DetailView):
    model=Farm
    success_url=reverse_lazy('index')
    context_object_name = 'farm'
    template_name='polls/detail.html'
    
class GrowthView(CreateView):
    global farm_id
    model=Growth
    fields=['pub_date','flower_part','growpoint_shape','leaf_size',
            'geodetic_form','stem_color','flower_size',
            'root_form','weekly_growth','fruit_load',
            'number_bloom','growpoint_leafcolor','flower_shape','flower_distance']
    template_name='polls/GrowthSurvey_create.html'
    context_object_name = 'farm'
    template_name_suffix='_create'
    
    def form_valid(self,form):
        form.instance.farm_id=farm_id
        if form.is_valid():
            form.instance.save()
            return redirect('/polls')
        else:
            return self.render_to_response({'form':form})

class ManageView(CreateView):
    global farm_id
    model=Manage
    fields=['pub_date','temp','DIF_AM','DIF_PM','D','N','HD','Pband','CO','Light',
            'WC','StartW','WEC','WRatio','WType','RHead',
            'RLeaf','RFruit','Overload','Geodetic','LAI','acc_light']
    template_name='polls/ManageSurvey_create.html'
    context_object_name = 'farm'
    template_name_suffix='_create'
    
    def form_valid(self,form):
        form.instance.farm_id=farm_id
        if form.is_valid():
            form.instance.save()
            return redirect('/polls')
        else:
            return self.render_to_response({'form':form})
    

polls/templates/polls/.ipynb_checkpoints/GrowthSurvey_create-checkpoint.html
<h1>{{ farm.farm_name }} </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="" method="POST">
    {% csrf_token %}
<table border="1">
    <p></p>
    입력 날짜 : <input type="date" name="pub_date">
	<th>생장</th>
	<th>-2</th>
	<th>-1</th>
	<th>0</th>
	<th>+1</th>
	<th>+2</th>
	<tr>
	    <td align = "center">개화부 경경</td>
	    <td align = "center"><input type="radio" name="flower_part" value="-2"></td>
	    <td align = "center"><input type="radio" name="flower_part" value="-1"></td>
	    <td align = "center"><input type="radio" name="flower_part" value="0"></td>
	    <td align = "center"><input type="radio" name="flower_part" value="1"></td>
	    <td align = "center"><input type="radio" name="flower_part" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">생장점 엽형태</td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="-2"></td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="-1"></td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="0"></td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="1"></td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">잎 크기</td>
	    <td align = "center"><input type="radio" name="leaf_size" value="-2"></td>
	    <td align = "center"><input type="radio" name="leaf_size" value="-1"></td>
	    <td align = "center"><input type="radio" name="leaf_size" value="0"></td>
	    <td align = "center"><input type="radio" name="leaf_size" value="1"></td>
	    <td align = "center"><input type="radio" name="leaf_size" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">측지 형태</td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="-2"></td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="-1"></td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="0"></td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="1"></td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">줄기 색</td>
	    <td align = "center"><input type="radio" name="stem_color" value="-2"></td>
	    <td align = "center"><input type="radio" name="stem_color" value="-1"></td>
	    <td align = "center"><input type="radio" name="stem_color" value="0"></td>
	    <td align = "center"><input type="radio" name="stem_color" value="1"></td>
	    <td align = "center"><input type="radio" name="stem_color" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">꽃 크기</td>
	    <td align = "center"><input type="radio" name="flower_size" value="-2"></td>
	    <td align = "center"><input type="radio" name="flower_size" value="-1"></td>
	    <td align = "center"><input type="radio" name="flower_size" value="0"></td>
	    <td align = "center"><input type="radio" name="flower_size" value="1"></td>
	    <td align = "center"><input type="radio" name="flower_size" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">뿌리형태/냄새</td>
	    <td align = "center"><input type="radio" name="root_form" value="-2"></td>
	    <td align = "center"><input type="radio" name="root_form" value="-1"></td>
	    <td align = "center"><input type="radio" name="root_form" value="0"></td>
	    <td align = "center"><input type="radio" name="root_form" value="1"></td>
	    <td align = "center"><input type="radio" name="root_form" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">주간절간생장</td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="-2"></td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="-1"></td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="0"></td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="1"></td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">착과부하수/m2</td>
	    <td align = "center"><input type="radio" name="fruit_load" value="-2"></td>
	    <td align = "center"><input type="radio" name="fruit_load" value="-1"></td>
	    <td align = "center"><input type="radio" name="fruit_load" value="0"></td>
	    <td align = "center"><input type="radio" name="fruit_load" value="1"></td>
	    <td align = "center"><input type="radio" name="fruit_load" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">개화꽃잎수</td>
	    <td align = "center"><input type="radio" name="number_bloom" value="-2"></td>
	    <td align = "center"><input type="radio" name="number_bloom" value="-1"></td>
	    <td align = "center"><input type="radio" name="number_bloom" value="0"></td>
	    <td align = "center"><input type="radio" name="number_bloom" value="1"></td>
	    <td align = "center"><input type="radio" name="number_bloom" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">생장점 엽색</td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="-2"></td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="-1"></td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="0"></td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="1"></td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">꽃자루 형태</td>
	    <td align = "center"><input type="radio" name="flower_shape" value="-2"></td>
	    <td align = "center"><input type="radio" name="flower_shape" value="-1"></td>
	    <td align = "center"><input type="radio" name="flower_shape" value="0"></td>
	    <td align = "center"><input type="radio" name="flower_shape" value="1"></td>
	    <td align = "center"><input type="radio" name="flower_shape" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">개화부위 거리</td>
	    <td align = "center"><input type="radio" name="flower_distance" value="-2"></td>
	    <td align = "center"><input type="radio" name="flower_distance" value="-1"></td>
	    <td align = "center"><input type="radio" name="flower_distance" value="0"></td>
	    <td align = "center"><input type="radio" name="flower_distance" value="1"></td>
	    <td align = "center"><input type="radio" name="flower_distance" value="2"></td>
	</tr>
    </table>
    <input type="submit" value="Survey">
</form>

polls/templates/polls/.ipynb_checkpoints/ManageSurvey_create-checkpoint.html
<h1>{{ farm.farm_name }} </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="POST">
    {% csrf_token %}
<table border="1">
    <p></p>
    입력 날짜 : <input type="date" name="pub_date">
    
	<th>환경관리</th>
	<th>데이터 입력</th>
	<tr>
	    <td align = "center">24시간평균온도</td>
	    <td align = "center"><input type="number" name="temp" value="20.0"></td>
	</tr>
	<tr>
	    <td align = "center">DIF 오전</td>
	    <td align = "center"><input type="number" name="DIF_AM" value="1.8"></td>
	</tr>
    <tr>
	    <td align = "center">DIF 오후</td>
	    <td align = "center"><input type="number" name="DIF_PM" value="1.4"></td>
	</tr>
    <tr>
	    <td align = "center">주간시작</td>
	    <td align = "center"><input type="time" name="D"></td>
	</tr>
    <tr>
	    <td align = "center">야간시작</td>
	    <td align = "center"><input type="time" name="N" ></td>
	</tr>
    <tr>
	    <td align = "center">HD</td>
	    <td align = "center"><input type="number" name="HD" value="2.5"></td>
	</tr>
    <tr>
	    <td align = "center">P-band</td>
	    <td align = "center"><input type="number" name="Pband" value="1.5"></td>
	</tr>
    <tr>
	    <td align = "center">CO2(주간최저)</td>
	    <td align = "center"><input type="number" name="CO" value="250"></td>
	</tr>
    <tr>
	    <td align = "center">차광</td>
	    <td align = "center"><input type="number" name="Light" value="0"></td>
	</tr>
    <tr>
	    <td align = "center">△WC(%)</td>
	    <td align = "center"><input type="number" name="WC" value="4"></td>
	</tr>
    <tr>
	    <td align = "center">급액시작</td>
	    <td align = "center"><input type="text" name="StartW" value="2:00"></td>
	</tr>
    <tr>
	    <td align = "center">급액종료</td>
	    <td align = "center"><input type="text" name="EndW" value="3:30"></td>
	</tr>
    <tr>
	    <td align = "center">급액EC/배지 EC</td>
	    <td align = "center"><input type="number" name="WEC" value="0.5"></td>
	</tr>
    <tr>
	    <td align = "center">배액율</td>
	    <td align = "center"><input type="number" name="WRatio" value="10"></td>
	</tr>
    <tr>
	    <td align = "center">급액방식</td>
        <td align = "center"> {{ form.WType }} </td>
	</tr>
    <tr>
	    <td align = "center">적심</td>
	    <td align = "center">{{ form.RHead }}</td>
	</tr>
    <tr>
	    <td align = "center">적엽</td>
	    <td align = "center">{{ form.RLeaf }}</td>
	</tr>
    <tr>
	    <td align = "center">적과</td>
	    <td align = "center">{{ form.RFruit }}</td>
	</tr>
    <tr>
	    <td align = "center">착과부하</td>
	    <td align = "center"><input type="number" name="Overload" value="1.5"></td>
	</tr>
    
    <tr>
	    <td align = "center">측지확보</td>
	    <td align = "center">{{ form.Geodetic }}
		</td>
	</tr>
    <tr>
	    <td align = "center">LAI</td>
	    <td align = "center"><input type="number" name="LAI" value="1.2"></td>
	</tr>
    <tr>
	    <td align = "center">누적광량</td>
	    <td align = "center"><input type="number" name="acc_light" value="800"></td>
	</tr>
    </table>
    <input type="submit" value="Survey">
</form>

polls/templates/polls/.ipynb_checkpoints/detail-checkpoint.html
<h1>{{ farm.farm_name }} </h1>

<ul>
	<a href="{% url 'polls:growth' farm.id %}">생육진단</a>
	<a href="{% url 'polls:manage' farm.id %}">환경조치</a>
</ul>

polls/templates/polls/.ipynb_checkpoints/farm_list-checkpoint.html
<!DOCTYPE HTML>
<HTML lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> 농가 선택 </h1>
<form action="" method="post">
{% csrf_token %}
{% if farm_list %}
    <ul>
    {% for farm in farm_list %}
        <button type="button" onclick="location.href='{% url 'polls:detail' farm.id %}'" value="farm.id" >{{ farm.farm_name }}</button>
    </ul>
    {% endfor %}
    
{% else %}
<p>No farms are available.</p>
{% endif %}
</form>
</body>
</HTML>

polls/templates/polls/GrowthSurvey_create.html
<h1>{{ farm.farm_name }} </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="" method="POST">
    {% csrf_token %}
<table border="1">
    <p></p>
    입력 날짜 : <input type="date" name="pub_date">
	<th>생장</th>
	<th>-2</th>
	<th>-1</th>
	<th>0</th>
	<th>+1</th>
	<th>+2</th>
	<tr>
	    <td align = "center">개화부 경경</td>
	    <td align = "center"><input type="radio" name="flower_part" value="-2"></td>
	    <td align = "center"><input type="radio" name="flower_part" value="-1"></td>
	    <td align = "center"><input type="radio" name="flower_part" value="0"></td>
	    <td align = "center"><input type="radio" name="flower_part" value="1"></td>
	    <td align = "center"><input type="radio" name="flower_part" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">생장점 엽형태</td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="-2"></td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="-1"></td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="0"></td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="1"></td>
	    <td align = "center"><input type="radio" name="growpoint_shape" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">잎 크기</td>
	    <td align = "center"><input type="radio" name="leaf_size" value="-2"></td>
	    <td align = "center"><input type="radio" name="leaf_size" value="-1"></td>
	    <td align = "center"><input type="radio" name="leaf_size" value="0"></td>
	    <td align = "center"><input type="radio" name="leaf_size" value="1"></td>
	    <td align = "center"><input type="radio" name="leaf_size" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">측지 형태</td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="-2"></td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="-1"></td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="0"></td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="1"></td>
	    <td align = "center"><input type="radio" name="geodetic_form" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">줄기 색</td>
	    <td align = "center"><input type="radio" name="stem_color" value="-2"></td>
	    <td align = "center"><input type="radio" name="stem_color" value="-1"></td>
	    <td align = "center"><input type="radio" name="stem_color" value="0"></td>
	    <td align = "center"><input type="radio" name="stem_color" value="1"></td>
	    <td align = "center"><input type="radio" name="stem_color" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">꽃 크기</td>
	    <td align = "center"><input type="radio" name="flower_size" value="-2"></td>
	    <td align = "center"><input type="radio" name="flower_size" value="-1"></td>
	    <td align = "center"><input type="radio" name="flower_size" value="0"></td>
	    <td align = "center"><input type="radio" name="flower_size" value="1"></td>
	    <td align = "center"><input type="radio" name="flower_size" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">뿌리형태/냄새</td>
	    <td align = "center"><input type="radio" name="root_form" value="-2"></td>
	    <td align = "center"><input type="radio" name="root_form" value="-1"></td>
	    <td align = "center"><input type="radio" name="root_form" value="0"></td>
	    <td align = "center"><input type="radio" name="root_form" value="1"></td>
	    <td align = "center"><input type="radio" name="root_form" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">주간절간생장</td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="-2"></td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="-1"></td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="0"></td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="1"></td>
	    <td align = "center"><input type="radio" name="weekly_growth" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">착과부하수/m2</td>
	    <td align = "center"><input type="radio" name="fruit_load" value="-2"></td>
	    <td align = "center"><input type="radio" name="fruit_load" value="-1"></td>
	    <td align = "center"><input type="radio" name="fruit_load" value="0"></td>
	    <td align = "center"><input type="radio" name="fruit_load" value="1"></td>
	    <td align = "center"><input type="radio" name="fruit_load" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">개화꽃잎수</td>
	    <td align = "center"><input type="radio" name="number_bloom" value="-2"></td>
	    <td align = "center"><input type="radio" name="number_bloom" value="-1"></td>
	    <td align = "center"><input type="radio" name="number_bloom" value="0"></td>
	    <td align = "center"><input type="radio" name="number_bloom" value="1"></td>
	    <td align = "center"><input type="radio" name="number_bloom" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">생장점 엽색</td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="-2"></td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="-1"></td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="0"></td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="1"></td>
	    <td align = "center"><input type="radio" name="growpoint_leafcolor" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">꽃자루 형태</td>
	    <td align = "center"><input type="radio" name="flower_shape" value="-2"></td>
	    <td align = "center"><input type="radio" name="flower_shape" value="-1"></td>
	    <td align = "center"><input type="radio" name="flower_shape" value="0"></td>
	    <td align = "center"><input type="radio" name="flower_shape" value="1"></td>
	    <td align = "center"><input type="radio" name="flower_shape" value="2"></td>
	</tr>
	<tr>
	    <td align = "center">개화부위 거리</td>
	    <td align = "center"><input type="radio" name="flower_distance" value="-2"></td>
	    <td align = "center"><input type="radio" name="flower_distance" value="-1"></td>
	    <td align = "center"><input type="radio" name="flower_distance" value="0"></td>
	    <td align = "center"><input type="radio" name="flower_distance" value="1"></td>
	    <td align = "center"><input type="radio" name="flower_distance" value="2"></td>
	</tr>
    </table>
    <input type="submit" value="Survey">
</form>

polls/templates/polls/detail.html
<h1>{{ farm.farm_name }} </h1>

<ul>
	<a href="{% url 'polls:growth' farm.id %}">생육진단</a>
	<a href="{% url 'polls:manage' farm.id %}">환경조치</a>
</ul>

polls/templates/polls/farm_list.html
<!DOCTYPE HTML>
<HTML lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> 농가 선택 </h1>
<form action="" method="post">
{% csrf_token %}
{% if farm_list %}
    <ul>
    {% for farm in farm_list %}
        <button type="button" onclick="location.href='{% url 'polls:detail' farm.id %}'" value="farm.id" >{{ farm.farm_name }}</button>
    </ul>
    {% endfor %}
    
{% else %}
<p>No farms are available.</p>
{% endif %}
</form>
</body>
</HTML>